### ISSUE TITLE
Exception after deletion of unmodified entity

### ISSUE THREAD

**Issue by gbrehmer** [hipster-labs/generator-jhipster-entity-audit#28] opened 2016-03-23 13:37 UTC
If an entity will be deleted before making any modifications, the lastModificationData is missing. Because modifiedDate of EntityAuditEvent is mandatory, the createdBy/createdAt-values could be used instead.

```
2016-03-23 14:16:45.967 DEBUG 5457 --- [Executor-2] d.i.r.w.c.a.AsyncEntityAuditEventWriter  : -------------- Post DELETE audit  --------------
Hibernate: select max(entityaudi0_.commit_version) as col_0_0_ from jhi_entity_audit_event entityaudi0_ where entityaudi0_.entity_type=? and entityaudi0_.entity_id=?
2016-03-23 14:16:45.971 ERROR 5457 --- [Executor-2] d.i.r.w.c.a.AsyncEntityAuditEventWriter  : Exception while persisting audit entity for User{...} error: {}

javax.validation.ConstraintViolationException: Validation failed for classes [domain.EntityAuditEvent] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='darf nicht null sein', propertyPath=modifiedDate, rootBeanClass=class domain.EntityAuditEvent, messageTemplate='{javax.validation.constraints.NotNull.message}'}
]
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:160)
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:95)
´´´

**Comment by deepu105** [comment] 2016-03-24 12:02
can you check with latest release?

**Comment by gbrehmer** [comment] 2016-03-24 12:10
I heck the sourcecode and dit not find any related changes:

EntityAuditEvent.modifiedDate has NotNull Annotation / table has notNullable constraint.
AsyncEntityAuditEventWriter still use getLastModifiedDate() for DELETE-Event. But LastModifiedDate will be only filled by @PreUpdate Events (Spring Data). But an INSERT on Entity creation can not fire such an event.

**Comment by deepu105** [comment] 2016-05-03 11:03
@gbrehmer would you like to do a PR to fix this?

**Comment by deepu105** [comment] 2016-06-24 09:00
I checked this and I dont find any issues. during a delete action the modified by and modified date values are set by spring and we read that in the `AsyncEntityAuditEventWriter` I tried and its working fine. 

![image](https://cloud.githubusercontent.com/assets/1107223/16333283/0b4eb416-3a2d-11e6-9f2b-7c3d98715b28.png)

Closing as I couldn't reproduce. plz update if you have more info

**Comment by deepu105** [comment] 2016-06-24 09:04
Ok sorry I spoke too fast. This happens only for the user entity since it was not created when this module was added

**Comment by deepu105** [comment] 2016-06-24 09:04
need to check further

**Comment by deepu105** [comment] 2016-06-24 09:07
Ok the issue is that the default users are created via liquibase and hence audit info is not captured

**Closed by deepu105** 2016-06-24 09:07 UTC

**Comment by deepu105** [comment] 2016-06-24 09:08
this needs to be updated in JHipster

**Comment by gbrehmer** [comment] 2016-06-24 11:24
You're right, sorry for any inconvenience. 
I didn't saw, that AbstractAuditingEntity set lastModifiedDate initially to Date.now. I was looking for methods calling the setter of lastModifiedDate ;) We are prefilling our database for other entities with liquibase, too.
