### ISSUE TITLE
JHipster Entity Audit Generator! v2.4.1 - TypeError: this.addEntityToCache is not a function

### ISSUE THREAD

**Issue by wsdrools** [hipster-labs/generator-jhipster-entity-audit#66] opened 2017-07-26 10:33 UTC
I am trying to add Entity Audit to my entity to a Angular4 JHipster project. 
After selecting the classes to add auditing features and answering Yes to adding audit log page for the entity, the system the following error:
TypeError: this.addEntityToCache is not a function at Object.addEntityToEhcache (E:\jhipsterdev\ng2\webOrderProject\WebOrdMono\node_modules\generator-jhipster\generators\generator-base.js:724:14)
    at child.writeBaseFiles (C:\Users\user\AppData\Roaming\npm\node_modules\generator-jhipster-entity-audit\generators\app\index.js:212:24)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\generator-jhipster-entity-audit\node_modules\yeoman-generator\lib\base.js:436:25)
    at C:\Users\user\AppData\Roaming\npm\node_modules\generator-jhipster-entity-audit\node_modules\yeoman-generator\node_modules\run-async\index.js:25:25
    at C:\Users\user\AppData\Roaming\npm\node_modules\generator-jhipster-entity-audit\node_modules\yeoman-generator\node_modules\run-async\index.js:24:19
    at C:\Users\user\AppData\Roaming\npm\node_modules\generator-jhipster-entity-audit\node_modules\yeoman-generator\lib\base.js:448:8
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Appreciate any suggestion on how to resolve this issue. 

Thanks in advance.

**Comment by willian-essenti** [comment] 2017-07-26 12:34
Same problem here, but with AngularJS frontend.

**Comment by cristian-spiescu** [comment] 2017-07-28 10:26
Same here. Duplicates #65 

Any help would be deeply appreciated!

Thanks.

**Comment by deepu105** [comment] 2017-07-28 18:37
This will not work for Angular4 as the code supports only AngularJS at the moment.
Please provide your applications `.yo-rc.json` and your entity config to reproduce this

**Comment by deepu105** [comment] 2017-07-28 18:38
duplicate of #65

**Closed by deepu105** 2017-07-28 18:38 UTC
